### ISSUE TITLE
Fehlermeldung: "The XML template has an error."

### ISSUE THREAD

**Issue by gesi3** [lhoffjann/ManuscriptAssistant#23]
Das Programm findet die XML-Vorlage nicht, s.

![grafik](https://github.com/lhoffjann/ManuscriptAssistant/assets/119319420/5f7661b6-8de7-404a-b92c-268b048e3394)

Vermutung von @lhoffjann : Die Vorlage wird nicht gefunden, weil der Pfad im Quellquode auf Linux gemützt ist, hier aber die Windows-Notation gebaucht wird.

**Comment by lhoffjann** [comment]
@gesi3 kannst du einmal probieren in der Vorlage `<facsimile/>` durch `<facsimile></facsimile>` zu ersetzen?

**Comment by gesi3** [comment]
@lhoffjann Habe ich soeben probiert, leider ohne Erfolg, die Fehlermeldung bleibt dieselbe und es wird keine XML-Datei erzeugt.

**Comment by lhoffjann** [comment]
War ein Versuch wert. danke! @Whatever0rg magst du das einmal auf deiner Kiste testen?

**Comment by Whatever0rg** [comment]
Kann ich tun, das wird aber vor dem Wochenende wahrscheinlich nicht passieren.

**Comment by lhoffjann** [comment]
@gesi3 wir haben leider eine "works on my maschine"-Situation. Wir nutzen noch dieses template hier: https://github.com/lhoffjann/ManuscriptAssistant/files/12290252/MS_transcript.txt - Ist das noch aktuell?

**Comment by gesi3** [comment]
@lhoffjann Die aktuelle Vorlage liegt immer hier im repo: https://gitlab.ub.uni-bielefeld.de/luhmann/luhmann-oxygen-framework-manuskripte/-/tree/master/vorlagen?ref_type=heads

Bei meinem lokalen gitlab-Verzeichnis ist das also immer dieser Pfad: ...\luhmann-oxygen-framework-manuskripte\vorlagen\MS_transcript.xml

Ich hänge die hier mal die aktuelle Datei an (die Endung ".txt" bitte wieder aus dem Dateinamen entfernen, die musste ich hinzufügen, weil GitHub keine .xml-Datei akzeptiert beim Hochladen):
[MS_transcript.xml.txt](https://github.com/lhoffjann/ManuscriptAssistant/files/14861857/MS_transcript.xml.txt)

**Comment by lhoffjann** [comment]
okay. ja, das scheint es auch nicht zu sein. die Dateien unterscheiden sich nur im Datum. Magst du deine .env posten (ohne gitlab secret)? 

Ich denke wir müssen wohl eine Debug Option mit einbauen.

**Comment by gesi3** [comment]
@lhoffjann Hier kommt die .env: 
[.env.txt](https://github.com/lhoffjann/ManuscriptAssistant/files/14873331/default.env.txt)

**Comment by lhoffjann** [comment]
Danke! hab den Fehler glaub ich gefunden. `path_xml_template_folder=` muss auf die Datei zeigen und nicht nur auf den Ordner. Der Name der Variable ist dort von uns einfach falsch gewählt worden. Issue ist erstellt: #25

**Comment by lhoffjann** [comment]
es reicht wenn du explizit auf die Datei verweist. wir sollten es trotzdem in der nächsten version anpassen.

**Comment by gesi3** [comment]
Sauber! Das war die Lösung, jetzt geht es wieder! Danke!
![grafik](https://github.com/lhoffjann/ManuscriptAssistant/assets/119319420/f23ab8fd-0c49-4f9c-8376-abcff2e75df1)
