### ISSUE TITLE
keine Zeilenumbrüche (lb) mehr im XML?

### ISSUE THREAD

**Issue by gesi3** [lhoffjann/ManuscriptAssistant#26]
@lhoffjann Mir ist an der frisch erstellten Datei (MS_3960.xml) von gestern aufgefallen, dass bei der Erstellung der XML-Datei keine Zeilenumbrüche (lb) in den OCR-Text eingefügt werden. In der txt-Datei aus der OCR-Erkennung sind diese drin, aber in der XML-Datei nicht mehr. Im Editor sieht das dann etwa so aus:
![Bildschirmfoto von 2024-04-09 07-35-21](https://github.com/lhoffjann/ManuscriptAssistant/assets/119319420/6478da61-6dcd-43e0-a2e1-27dc1acbbcd3)
Das ist nicht so schön, weil man die Zeilenumbrüche jetzt händisch eintragen muss...Gibt es eine Möglichkeit, die lb wieder automatisch zu setzen?

**Comment by lhoffjann** [comment]
Ah verdammt. wir wollten das Pagebreak Feature entfernen, richtig? Ich bau heute Abend eine neue Version, wo das Feature wieder drin ist.

**Comment by lhoffjann** [comment]
https://github.com/lhoffjann/ManuscriptAssistant/blob/main/src/main/java/org/lhoffjann/Manuscript/XMLCreator.java#L38 
ja, wenn ein `-` am ende der Zeile steht wird ein inWord eingefügt, aber das `-` bleibt im Text stehen.

**Comment by gesi3** [comment]
Kriegst du das `-` da noch weg oder ist das zu kompliziert?

**Comment by gesi3** [comment]
Ach, nochmal kurz zur Sicherheit, weil du es oben falsch geschrieben und ich daraufhin sogar noch bestätigt habe: Nicht das pagebreak-Feature (pb) soll raus, sondern nur das paragraph-Feature (p) für die Absatzstruktur. Das soll raus, aber die pb und lb sollen unbedingt drinbleiben!

**Comment by lhoffjann** [comment]
https://github.com/lhoffjann/ManuscriptAssistant/releases/tag/0.0.2 - müsste jetzt wieder funktionieren. mit pb und lb. hab auch den env namen für die xml angepasst. bitte bei dir updaten.

**Comment by gesi3** [comment]
Wunderbar, die Umbenennung in der .env habe ich durchgeführt und das Programm läuft so wie es soll! Schön, dass auch das Entfernen der "-" bei lb inWord geklappt hat!

**Comment by lhoffjann** [comment]
Top. freut mich!
