### ISSUE TITLE
Qualität der pdf nochmals verringern

### ISSUE THREAD

**Issue by gesi3** [lhoffjann/ManuscriptAssistant#3]
@lhoffjann Kannst du die Quali der pdfs nochmals um ein paar Prozent verringern? Die Dateien sind mir immer noch etwas zu groß. Vielleicht werden sie ja auch schon automatisch kleiner, wenn die zusätzlichen Ränder (s. #2) nicht mehr enthalten sind...das müssen wir vielleicht zuerst noch testen.

**Comment by Whatever0rg** [comment]
Faktor der Kompression sollte über einen Wert in der .env verändert werden können.

**Comment by Whatever0rg** [comment]
Done!
