### ISSUE TITLE
kleines Problem mit dem Scanprogramm: voranstehenden 0 bei der MS-ID wird nicht übernommen

### ISSUE THREAD

**Issue by gesi3** [lhoffjann/ManuscriptAssistant#5]
Problem: Soll ein Ms. mit einer ID unterhalb von 1000 gescannt werden, legt das Scanprogramm trotz korrekter ID-Eingabe, z.B. 0156, die Dateien ohne die voranstehen 0 an. Die Dateien sehen also dann alle so aus: MS_156_0001_.tif
Auch das GitLab-Issue wird entsprechend mit der falschen, nur dreistelligen ID angelegt.

**Comment by lhoffjann** [comment]
besteht dieses Problem noch? ich hatte das scan program ja einmal komplett ueberarbeitet.
