### ISSUE TITLE
In welchen Dateien kann ich die Issuevorlage ändern? (ManuscriptAssistant & Scanprogramm)

### ISSUE THREAD

**Issue by gesi3** [lhoffjann/ManuscriptAssistant#6]
Problem: Es kommt wohl doch hin und wieder vor, dass wir die GitLab-Issuevorlage etwas ändern müssen. Spricht etwas dagegen, dass ich das bei Scanprogeamm und beim ManuscriptAssistant selbst ändere? Wenn das geht, könnstest du mir die Dateien und Verzeichnisse hier noch einmal nennen, in denen ich die Änderungen vornehmen kann?

**Comment by gesi3** [comment]
@lhoffjann Die Issurstrukturvorlage muss dringend mal aktualisiert werden. Hier ist die aktuelle Version zu finden: https://gitlab.ub.uni-bielefeld.de/luhmann/scan_automatisierung/-/issues/1

**Comment by lhoffjann** [comment]
closed because of duplication
